services:
    phpBB\SessionsAuthBundle\EventListener\TablePrefixListener:
        public: false
        arguments: ["%phpbb.database.prefix%"]
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }

    phpBB\SessionsAuthBundle\Security\PhpbbSessionAuthenticator:
        public: false
        arguments:
            - "%phpbb.session.cookie_name%"
            - "%phpbb.session.login_page%"
            - "%phpbb.session.force_login%"
            - "@phpBB\\SessionsAuthBundle\\Security\\PhpbbUserProvider"

    phpBB\SessionsAuthBundle\Security\PhpbbUserProvider:
        public: false
        arguments: ["@doctrine", "%phpbb.database.entity_manager%"]
        calls: [[setRoles, ["%phpbb.roles%"]]]
